[workspace]
resolver = "2"
members = ["crates/proto", "crates/server", "crates/agent", "crates/fwctl", "crates/ops-agent"]

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/louishwh/machine-monitor"

[workspace.dependencies]
fw-proto = { path = "crates/proto", version = "0.1.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "signal"] }
anyhow = "1"
thiserror = "1"
ed25519-dalek = "2"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
